services:
  build:
    image: podman-build
    build: .
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - TZ=Asia/Seoul
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sh -c "make clean && make BUILDTAGS='cni seccomp systemd apparmor' PREFIX=/usr"